"""added role column

Revision ID: 30cf647fd9a1
Revises: d8495f0ba526
Create Date: 2025-03-08 15:55:51.977138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cf647fd9a1'
down_revision = 'd8495f0ba526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('user', schema=None) as batch_op:
        op.add_column('user', sa.Column('role', sa.String(length=20), nullable=False, server_default='student'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
